bidikmisi/routes/web.php
<?php
//User Routes
Route::group(['namespace'=>'User'],function(){
	Route::get('/','HomeController@index')->name('user.home');
	Route::get('berita/{slug}','HomeController@show')->name('berita');
	Route::resource('user/jadwal_visitasi','VisitasiController');
	Route::resource('user/banyaksiswa_persekolah','BanyakSiswaPerSekolahController');
	Route::post('user/banyaksiswa_persekolahshow','BanyakSiswaPerSekolahController@show')->name('banyaksiswa_persekolah.show');
	Route::resource('user/banyaksiswa_perkota','BanyakSiswaPerKotaController');
	Route::post('user/banyaksiswa_perkotashow','BanyakSiswaPerKotaController@show')->name('banyaksiswa_perkota.show');
	Route::resource('user/banyaksiswa_perprovinsi','BanyakSiswaPerProvinsiController');
	Route::post('user/banyaksiswa_perprovinsishow','BanyakSiswaPerProvinsiController@show')->name('banyaksiswa_perprovinsi.show');
	Route::resource('user/laravelgooglechart','LaravelGoogleGraphController');
	Route::post('user/laravelgooglechartshow','LaravelGoogleGraphController@show')->name('laravelgooglechart.show');
	Route::resource('user/laravelgooglechart2','LaravelGoogleGraph2Controller');
	Route::post('user/laravelgooglechart2show','LaravelGoogleGraph2Controller@show')->name('laravelgooglechart2.show');
	Route::resource('user/prestasi_ekskul','PrestasiEkskulController');
	Route::post('user/prestasi_ekskulshow','PrestasiEkskulController@show')->name('prestasi_ekskul.show');
	Route::resource('user/validasi_nilai','ValidasiNilaiController');
	Route::post('user/validasi_nilaishow','ValidasiNilaiController@show')->name('validasi_nilai.show');
	Route::resource('user/validasi_jurusan','ValidasiJurusanController');
	Route::post('user/validasi_jurusanshow','ValidasiJurusanController@show')->name('validasi_jurusan.show');
});
//Dosen Route
Route::group(['namespace'=>'Dosen'],function(){
	Route::get('dosen/home','HomeController@index')->name('dosen.home');
	Route::resource('dosen/data-dosen','DosenController');
	Route::resource('dosen/data-nilai','NilaiController');
	Route::post('dosen/data-nilai-show','NilaiController@show')->name('data-nilai.show');
	Route::resource('dosen/data-pendaftaran','PendaftaranController');
	Route::post('dosen/data-pendaftaran-show','PendaftaranController@show')->name('data-pendaftaran.show');
	Route::resource('dosen/data-penghasilan_ortu','Penghasilan_OrtuController');
	Route::post('dosen/data-penghasilan_ortu-show','Penghasilan_OrtuController@show')->name('data-penghasilan_ortu.show');
	Route::resource('dosen/data-rumah','RumahController');
	Route::post('dosen/data-rumah-show','RumahController@show')->name('data-rumah.show');
	Route::resource('dosen/data-sekolah','SekolahController');
	Route::post('dosen/data-sekolah-show','SekolahController@show')->name('data-sekolah.show');
	Route::resource('dosen/data-siswa','SiswaController');
	Route::post('dosen/data-siswa-show','SiswaController@show')->name('data-siswa.show');
	Route::resource('dosen/data-visitasi','VisitasiController');

	 //Auth Dosen
	//Route::get('/signinvisitor', 'Auth\LoginController@showLoginForm')->name('signinvisitor');
	//Route::post('/signinvisitor', 'Auth\LoginController@login');
	//Route::post('logout','Auth\LoginController@logout')->name('logout');
});
//Pengelola atau Admin Route
Route::group(['namespace'=>'Pengelola'],function(){
	Route::get('pengelola/home','HomeController@index')->name('pengelola.home');
	Route::get('pengelola/ieds','IedsController@index')->name('pengelola.ieds');
	Route::get('pengelola/skorfuzzy','SkorfuzzyController@index')->name('pengelola.skorfuzzy');
	Route::get('pengelola/importfuzzy','SkorfuzzyController@indexImport')->name('pengelola.importfuzzy');
	Route::post('pengelola/kuotafuzzy','SkorfuzzyController@kuota')->name('pengelola.kuotafuzzy');
	Route::resource('pengelola/dosen','DosenController');
	Route::resource('pengelola/user','UserController');
	Route::resource('pengelola/datasau','SaudaraController');
	Route::resource('pengelola/dataketsau','KetsaudaraController');
	Route::resource('pengelola/datafoto','DatafotoController');
	Route::resource('pengelola/organisasi','OrganisasiController');
	Route::resource('pengelola/catatan','CatatanController');
	Route::resource('pengelola/berita','BeritaController');
	Route::resource('pengelola/dosen','DosenController');
	Route::resource('pengelola/nilai','NilaiController');
	Route::post('pengelola/nilaipertahun','NilaiController@show')->name('nilai.pertahun');
	Route::resource('pengelola/pendaftaran','PendaftaranController');
	Route::post('pengelola/pendaftaranpertahun','PendaftaranController@show')->name('pendaftaran.pertahun');
	Route::resource('pengelola/pengelola','PengelolaController');
	Route::resource('pengelola/penghasilan_ortu','Penghasilan_OrtuController');
	Route::post('pengelola/penghasilan_ortupertahun','Penghasilan_OrtuController@show')->name('penghasilan_ortu.pertahun');
	Route::resource('pengelola/rumah','RumahController');
	Route::post('pengelola/rumahpertahun','RumahController@show')->name('rumah.pertahun');
	Route::resource('pengelola/sekolah','SekolahController');
	Route::post('pengelola/sekolahpertahun','SekolahController@show')->name('sekolah.pertahun');
	Route::resource('pengelola/siswa','SiswaController');
	Route::post('pengelola/siswapertahun','SiswaController@show')->name('siswa.pertahun');
	Route::resource('pengelola/visitasi','VisitasiController');
	Route::resource('pengelola/prestasiekskul','PrestasiEkskulController');
	Route::post('pengelola/prestasiekskulshow','PrestasiEkskulController@show')->name('prestasiekskul.show');
	Route::resource('pengelola/banyaksiswapersekolah','BanyakSiswaPerSekolahController');
	Route::post('pengelola/banyaksiswapersekolahshow','BanyakSiswaPerSekolahController@show')->name('banyaksiswapersekolah.show');
	Route::resource('pengelola/banyaksiswaperprovinsi','BanyakSiswaPerProvinsiController');
	Route::post('pengelola/banyaksiswaperprovinsishow','BanyakSiswaPerProvinsiController@show')->name('banyaksiswaperprovinsi.show');
	Route::resource('pengelola/siswaperprodi','SiswaPerProdiController');
	Route::post('pengelola/siswaperprodishow','SiswaPerProdiController@show')->name('siswaperprodi.show');
	Route::resource('pengelola/banyaksiswaperkota','BanyakSiswaPerKotaController');
	Route::post('pengelola/banyaksiswaperkotashow','BanyakSiswaPerKotaController@show')->name('banyaksiswaperkota.show');
	Route::resource('pengelola/validasinilai','DataNilaiValidController');
	Route::post('pengelola/validasinilaishow','DataNilaiValidController@show')->name('validasinilai.show');
	Route::resource('pengelola/datanilaitidakvalid','DataNilaiTidakValidController');
	Route::resource('pengelola/laravel_google_chart', 'LaravelGoogleGraphController');
	Route::post('pengelola/laravel_google_chartshow','LaravelGoogleGraphController@show')->name('laravel_google_chart.show');
	Route::resource('pengelola/laravel_google_chart2', 'LaravelGoogleGraph2Controller');
	Route::post('pengelola/laravel_google_chart2show','LaravelGoogleGraph2Controller@show')->name('laravel_google_chart2.show');
	Route::resource('pengelola/validasijurusan','ValidasiJurusanController');
	Route::post('pengelola/validasijurusanshow','ValidasiJurusanController@show')->name('validasijurusan.show');

	Route::resource('pengelola/validasipenghasilan','ValidasiPenghasilanController');

	Route::get('pengelola/validatejurusan/validasi','ValidasiJurusanController@vld');
	Route::post('pengelola/validpenghasilan', 'ValidasiPenghasilanController@vld');
	Route::get('pengelola/validatenilai/validasi','DataNilaiValidController@vld');
	Route::resource('pengelola/jurusan', 'UpdateJurusanController');
	
	//Import Export Data Routes
	Route::get('pengelola/iofile','ImportExportController@index')->name('pengelola.importexport');
	Route::post('importsiswa', 'SiswaController@siswaImport')->name('siswa.import');
	Route::get('exportsiswa', 'SiswaController@siswaExport')->name('siswa.export');
	Route::post('importdosen', 'DosenController@Import')->name('dosen.import');
	Route::get('exportdosen', 'DosenController@Export')->name('dosen.export');
	Route::post('importvisitasi', 'VisitasiController@Import')->name('visitasi.import');
	Route::get('exportvisitasi', 'VisitasiController@Export')->name('visitasi.export');
	Route::post('importfuzzy','SkorfuzzyController@Import')->name('fuzzy.import');

	//Auth Pengelola
	Route::get('/signin', 'Auth\LoginController@showLoginForm')->name('signin');
	Route::post('/signin', 'Auth\LoginController@login');
	Route::post('logout','Auth\LoginController@logout')->name('logout');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

bidikmisi/app/Http/Controllers/Dosen/SiswaController.php
<?php

namespace App\Http\Controllers\Dosen;

use App\Http\Controllers\Controller;
use App\Model\pengelola\siswa;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Auth;

class SiswaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:pengelola');
    }

    public function index()
    {
        $user = Auth::user()->nidn;
        $siswas = siswa::where('id_visitor1',$user)->orWhere('id_visitor2',$user)->get();
        return view('dosen.data-siswa',compact('siswas'));
    }

    public function show(Request $request)
    {
        $siswas = DB::table('siswas')
        ->whereYear('tgl_daftar', '=', $request->tahun)
        ->get();
        return view('dosen.data-siswa-show',compact('siswas'));
    }
}

bidikmisi/app/Http/Controllers/Pengelola/BanyakSiswaPerKotaController.php
<?php

namespace App\Http\Controllers\Pengelola;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\pengelola\sekolah;
use Illuminate\Support\Facades\DB;
use PDF;

class BanyakSiswaPerKotaController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
        $showprov = DB::table('sekolahs')
        ->select('prov_sklh')
        ->groupBy('prov_sklh')
        ->get();
    	$sekolahs = DB::table('sekolahs')
        ->select('kota_sklh', DB::raw('count(*) as total'))
        ->groupBy('kota_sklh')
        ->get();
        return view('pengelola.banyaksiswaperkota',compact('sekolahs','showprov'));
    }

    public function show(Request $request){
        $prov_sklh = $request->prov_sklh;
        $tahun = $request->tahun;
        $sekolahs = DB::table('sekolahs')
        ->select('kota_sklh', DB::raw('count(*) as total'))
        ->where('prov_sklh', '=', $request->prov_sklh)
        ->whereYear('tgl_daftar', '=', $request->tahun)
        ->groupBy('kota_sklh')
        ->get();
        $pdf = PDF::loadView('pengelola.banyaksiswaperkotashow', compact('sekolahs','tahun','prov_sklh'));
        return $pdf->stream('banyaksiswaperkota.pdf');
    }


}

bidikmisi/app/Http/Controllers/Pengelola/BanyakSiswaPerProvinsiController.php
<?php

namespace App\Http\Controllers\Pengelola;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\pengelola\sekolah;
use Illuminate\Support\Facades\DB;
use PDF;

class BanyakSiswaPerProvinsiController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
    	$sekolahs = DB::table('sekolahs')
        ->select('prov_sklh', DB::raw('count(*) as total'))
        ->groupBy('prov_sklh')
        ->get();
        return view('pengelola.banyaksiswaperprovinsi',compact('sekolahs'));
    }
    public function show(Request $request)
    {
        $tahun = $request->tahun;
        $sekolahs = DB::table('sekolahs')
        ->select('prov_sklh', DB::raw('count(*) as total'))
        ->whereYear('tgl_daftar', '=', $request->tahun)
        ->groupBy('prov_sklh')
        ->get();
        $pdf = PDF::loadView('pengelola.banyaksiswaperprovinsishow', compact('sekolahs','tahun'));
        return $pdf->stream('banyaksiswaperprovinsi.pdf');
    }
}

bidikmisi/app/Http/Controllers/Pengelola/BanyakSiswaPerSekolahController.php
<?php

namespace App\Http\Controllers\Pengelola;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\pengelola\sekolah;
use Illuminate\Support\Facades\DB;
use PDF;

class BanyakSiswaPerSekolahController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
    	$sekolahs = DB::table('sekolahs')
        ->select('nama_sklh', DB::raw('count(*) as total'))
        ->groupBy('nama_sklh')
        ->get();
        return view('pengelola.banyaksiswapersekolah',compact('sekolahs'));
    }
    public function show(Request $request)
    {
        $tahun = $request->tahun;
        $sekolahs = DB::table('sekolahs')
        ->select('nama_sklh', DB::raw('count(*) as total'))
        ->whereYear('tgl_daftar', '=', $request->tahun)
        ->groupBy('nama_sklh')
        ->get();
        $pdf = PDF::loadView('pengelola.banyaksiswapersekolahshow', compact('sekolahs','tahun'));
        return $pdf->stream('banyaksiswapersekolah.pdf');
    }
    	
}

bidikmisi/app/Http/Controllers/Pengelola/BeritaController.php
<?php

namespace App\Http\Controllers\Pengelola;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\pengelola\berita;

class BeritaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
        $beritas = berita::all();
        return view('pengelola.berita.show',compact('beritas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('pengelola.berita.berita');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'judul'=>'required',
            'isi'=>'required',
            ]);
        $berita = new berita;
        $berita->judul=$request->judul;
        $berita->isi=$request->isi;
        $berita->slug=str_slug($request->judul);
        $berita->save();

        return redirect(route('berita.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $berita=berita::where('id',$id)->first();

        return view('pengelola.berita.edit',compact('berita'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'judul'=>'required',
            'isi'=>'required',
            ]);

         $berita = berita::find($id);
        $berita->judul=$request->judul;
        $berita->isi=$request->isi;
        $berita->slug=str_slug($request->judul);
        $berita->save();

        return redirect(route('berita.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        berita::where('id',$id)->delete();
        return redirect()->back();
    }
}

bidikmisi/app/Http/Controllers/Pengelola/DatafotoController.php
<?php

namespace App\Http\Controllers\Pengelola;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\pengelola\data_foto;

class DatafotoController extends Controller
{
    public function __construct()
    {
    	$this->middleware('auth:pengelola');
    }

    public function index()
    {
    	$datafoto = data_foto::all();
    	return view('pengelola.datafoto.show', compact('datafoto'));
    }
  
    public function destroy($id)
    {
        data_foto::where('id_foto',$id)->delete();
        return redirect()->back();
    }
}

bidikmisi/app/Http/Controllers/Pengelola/IedsController.php
<?php

namespace App\Http\Controllers\Pengelola;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class IedsController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
    	return view('pengelola/ieds');
    }
}

bidikmisi/app/Http/Controllers/Pengelola/PrestasiEkskulController.php
<?php

namespace App\Http\Controllers\Pengelola;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\pengelola\nilai;
use PDF;

class PrestasiEkskulController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
        $nilais = nilai::where('pres_ekskul','!=', '-')->get();
        return view('pengelola.prestasiekskul',compact('nilais'));
    }
    public function show(Request $request)
    {
        $tahun = $request->tahun;
        $nilais = nilai::where('pres_ekskul','!=', '-')
        ->whereYear('tgl_daftar', '=', $request->tahun)
		->get();
        $pdf = PDF::loadView('pengelola.prestasiekskulshow', compact('nilais','tahun'));
        return $pdf->stream('prestasiekskul.pdf');
    }
}

bidikmisi/resources/views/pengelola/siswa/edit.blade.php
@extends('pengelola.layouts.app')

@section('main-content')
<div class="page-content-wrap">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-colorful">
        <div class="panel-heading">
          <h3 class="panel-title">Form Edit Siswa</h3>
        </div>

        @include('includes.messages')

        <form role="form" action="{{ route('siswa.update',$siswa->nisn)}}" method="post" class="form-horizontal">
          {{ csrf_field()}}
          {{ method_field('PATCH')}}
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="nisn">NISN</label>
              <div class="col-md-9 col-xs-12">
                <input type="text" class="form-control" id="nisn" name="nisn" placeholder="NISN" value="{{$siswa->nisn}}">
              </div>
            </div>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="nama_siswa">Nama siswa</label>
              <div class="col-md-9 col-xs-12">
                <input type="text" class="form-control" id="nama_siswa" name="nama_siswa" placeholder="nama_siswa" value="{{ $siswa->nama_siswa}}">
              </div>
            </div>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="tempat_lahir">Tempat Lahir</label>
              <div class="col-md-9 col-xs-12">
                <input type="text" class="form-control" id="tempat_lahir" name="tempat_lahir" placeholder="tempat_lahir" value="{{ $siswa->tempat_lahir}}">
              </div>
            </div>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="tgl_lahir">Tanggal Lahir</label>
              <div class="col-md-9 col-xs-12">
                <input type="date" class="form-control" id="tgl_lahir" name="tgl_lahir" placeholder="tgl_lahir" value="{{ $siswa->tgl_lahir}}">
              </div>
            </div>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="jekel">Jenis Kelamin</label>
              <div class="col-md-9 col-xs-12">
                <label class="check"><input type="radio" class="iradio" name="jekel" value="L" {{$siswa->jekel == 'L' ? 'checked' :''}}>Laki-Laki</label>
                <br>
                <label class="check"><input type="radio" class="iradio" name="jekel" value="P" {{$siswa->jekel == 'P' ? 'checked' :''}}>Perempuan</label>
              </div>
            </div>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="no_hp">No. HP</label>
              <div class="col-md-9 col-xs-12">
                <input type="text" class="form-control" id="no_hp" name="no_hp" placeholder="no hp" value="{{ $siswa->no_hp}}">
              </div>
            </div>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="no_telp">No. Telp</label>
              <div class="col-md-9 col-xs-12">
                <input type="text" class="form-control" id="no_telp" name="no_telp" placeholder="no telp" value="{{ $siswa->no_telp}}">
              </div>
            </div>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="alamat">Alamat</label>
              <div class="col-md-9 col-xs-12">
                <textarea id="alamat" name="alamat" class="form-control" rows="5">{{ $siswa->alamat}}</textarea>
              </div>
            </div>
          </div>
          <div class="panel-body">
           <div class="form-group">
            <label class="col-md-2 col-xs-12 control-label" for="tgl_daftar">Tanggal Daftar</label>
            <div class="col-md-9 col-xs-12">
              <input type="datetime" class="form-control" id="tgl_daftar" name="tgl_daftar" placeholder="tanggal daftar" value="{{ $siswa->tgl_daftar}}">
            </div>
          </div>
        </div>
        <div class="panel-footer">
          <button type="submit" class="btn btn-primary">Simpan</button>
          <a href='{{route("siswa.index")}}' class="btn btn-warning">Kembali</a>
        </div>
      </form>
    </div>
  </div>
</div>
</div>
@endsection

bidikmisi/resources/views/pengelola/siswa/pertahun.blade.php
@extends('pengelola.layouts.app')

@section('head')
<!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('pengelola/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }} ">
@endsection

@section('main-content')
<div class="content-wrapper">

    <!-- Main content -->
    <section class="content container-fluid">

      <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Data Siswa</h3>
             
              
              {{-- <a class='col-lg-offset-10 btn btn-success' href="{{ route('siswa.create')}}">Tambah Siswa</a> --}}
            </div>
        
            <div class="box-body">
              <table id="myTable" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th width="7%">No.</th>
                  <th>NISN</th>
                  <th>Nama Siswa</th>
                  <th>Tempat Lahir</th>
                  <th>Tanggal Lahir</th>
                  <th>JK</th>
                  <th>No. HP</th>
                  <th>No. Telp</th>
                  <th>Alamat</th>
                  <th>Tanggal Daftar</th>
                  <th width="7%">Edit</th>
                  <th width="7%">Delete</th>
                </tr>
                </thead>
                <tbody>
                  @foreach ($siswas as $siswa)
                  <tr>
                    <td>{{ $loop->index + 1 }}</td>
                    <td>{{ $siswa->nisn }}</td>
                    <td>{{ $siswa->nama_siswa }}</td>
                    <td>{{ $siswa->tempat_lahir }}</td>
                    <td>{{ $siswa->tgl_lahir }}</td>
                    <td>{{ $siswa->jekel }}</td>
                    <td>{{ $siswa->no_hp }}</td>
                    <td>{{ $siswa->no_telp }}</td>
                    <td>{{ $siswa->alamat }}</td>
                    <td>{{ $siswa->tgl_daftar }}</td>
                    <td><a href="{{route('siswa.edit',$siswa->id)}}"><span class="glyphicon glyphicon-edit"></span></a></td>
                     <td>
                      <form id="delete-form-{{ $siswa->id }}" method="post" action="{{route('siswa.destroy',$siswa->id)}}" style="display: none">
                        {{csrf_field()}}
                        {{method_field('DELETE')}}
                      </form>
                      <a href="" onclick="
                      if(confirm('Yakin Ingin Menghapus Data siswa?'))
                        {
                          event.preventDefault();
                          document.getElementById('delete-form-{{ $siswa->id }}').submit();
                        } else {
                          event.preventDefault();
                        }"><span class="glyphicon glyphicon-trash"></span></a>
                        
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table> 
            </div>
          </div>

        </div>
      </div>
      <div class="box-footer">
        <a href='{{route('siswa.index')}}' class="btn btn-warning">Kembali</a>
      </div>
    </section>

    </section>
    <!-- /.content -->
  </div>

@endsection

@section('script')
<!-- DataTables -->
<script src="{{ asset('pengelola/bower_components/datatables.net/js/jquery.dataTables.min.js') }} "></script>
<script src="{{ asset('pengelola/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }} "></script>
<script>
  $(function () {
    $('#myTable').DataTable()
  })
</script>
@endsection

bidikmisi/resources/views/pengelola/siswa/show.blade.php
@extends('pengelola.layouts.app')

@section('main-content')
<div class="page-content-wrap">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-colorful animated fadeIn">
        <div class="panel-heading">
          <h3 class="panel-title">Data Siswa</h3>
          <a class='col-lg-offset-10 btn btn-success' href="{{ route('siswa.create')}}">Tambah Siswa</a>
        </div>
        <div class="panel-body table-responsive">
          <table class="table datatable table-hover">
            <thead>
              <tr>
                <th>No.</th>
                <th>NISN</th>
                <th>Nama Siswa</th>
                <th>Tempat Lahir</th>
                <th>Tanggal Lahir</th>
                <th>JK</th>
                <th>No. HP</th>
                <th>No. Telp</th>
                <th>Alamat</th>
                <th>Tanggal Daftar</th>
                <th width="5%">Aksi</th>
              </tr>
            </thead>
            <tbody>
              @foreach ($siswas as $siswa)
              <tr>
                <td>{{ $loop->index + 1 }}</td>
                <td>{{ $siswa->nisn }}</td>
                <td>{{ $siswa->nama_siswa }}</td>
                <td>{{ $siswa->tempat_lahir }}</td>
                <td>{{ $siswa->tgl_lahir }}</td>
                <td>{{ $siswa->jekel }}</td>
                <td>{{ $siswa->no_hp }}</td>
                <td>{{ $siswa->no_telp }}</td>
                <td>{{ $siswa->alamat }}</td>
                <td>{{ $siswa->tgl_daftar }}</td>
                <td><a href="{{route('siswa.edit',$siswa->nisn)}}"><span class="glyphicon glyphicon-edit"></span></a>
                  <form id="delete-form-{{ $siswa->nisn }}" method="post" action="{{route('siswa.destroy',$siswa->nisn)}}" style="display: none">
                    {{csrf_field()}}
                    {{method_field('DELETE')}}
                  </form>
                  <a href="" onclick="
                  if(confirm('Yakin Ingin Menghapus Data siswa?'))
                  {
                    event.preventDefault();
                    document.getElementById('delete-form-{{ $siswa->nisn }}').submit();
                  } else {
                    event.preventDefault();
                  }"><span class="glyphicon glyphicon-trash"></span></a>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table> 
        </div>
      </div>
    </div>
  </div>
  <!-- /.content -->
</div>

@endsection

@section('script')
<!-- DataTables -->

<script type="text/javascript" src="{{asset('js/plugins/datatables/jquery.dataTables.min.js')}}"></script> 
@endsection