bidikmisi/routes/web.php
<?php
//User Routes
Route::group(['namespace'=>'User'],function(){
	Route::get('/','HomeController@index')->name('user.home');
	Route::get('berita/{slug}','HomeController@show')->name('berita');
	Route::resource('user/jadwal_visitasi','VisitasiController');
	Route::resource('user/banyaksiswa_persekolah','BanyakSiswaPerSekolahController');
	Route::post('user/banyaksiswa_persekolahshow','BanyakSiswaPerSekolahController@show')->name('banyaksiswa_persekolah.show');
	Route::resource('user/banyaksiswa_perkota','BanyakSiswaPerKotaController');
	Route::post('user/banyaksiswa_perkotashow','BanyakSiswaPerKotaController@show')->name('banyaksiswa_perkota.show');
	Route::resource('user/banyaksiswa_perprovinsi','BanyakSiswaPerProvinsiController');
	Route::post('user/banyaksiswa_perprovinsishow','BanyakSiswaPerProvinsiController@show')->name('banyaksiswa_perprovinsi.show');
	Route::resource('user/laravelgooglechart','LaravelGoogleGraphController');
	Route::post('user/laravelgooglechartshow','LaravelGoogleGraphController@show')->name('laravelgooglechart.show');
	Route::resource('user/laravelgooglechart2','LaravelGoogleGraph2Controller');
	Route::post('user/laravelgooglechart2show','LaravelGoogleGraph2Controller@show')->name('laravelgooglechart2.show');
	Route::resource('user/prestasi_ekskul','PrestasiEkskulController');
	Route::post('user/prestasi_ekskulshow','PrestasiEkskulController@show')->name('prestasi_ekskul.show');
	Route::resource('user/validasi_nilai','ValidasiNilaiController');
	Route::post('user/validasi_nilaishow','ValidasiNilaiController@show')->name('validasi_nilai.show');
	Route::resource('user/validasi_jurusan','ValidasiJurusanController');
	Route::post('user/validasi_jurusanshow','ValidasiJurusanController@show')->name('validasi_jurusan.show');
});
//Dosen Route
Route::group(['namespace'=>'Dosen'],function(){
	Route::get('dosen/home','HomeController@index')->name('dosen.home');
	Route::resource('dosen/data-dosen','DosenController');
	Route::resource('dosen/data-nilai','NilaiController');
	Route::post('dosen/data-nilai-show','NilaiController@show')->name('data-nilai.show');
	Route::resource('dosen/data-pendaftaran','PendaftaranController');
	Route::post('dosen/data-pendaftaran-show','PendaftaranController@show')->name('data-pendaftaran.show');
	Route::resource('dosen/data-penghasilan_ortu','Penghasilan_OrtuController');
	Route::post('dosen/data-penghasilan_ortu-show','Penghasilan_OrtuController@show')->name('data-penghasilan_ortu.show');
	Route::resource('dosen/data-rumah','RumahController');
	Route::post('dosen/data-rumah-show','RumahController@show')->name('data-rumah.show');
	Route::resource('dosen/data-sekolah','SekolahController');
	Route::post('dosen/data-sekolah-show','SekolahController@show')->name('data-sekolah.show');
	Route::resource('dosen/data-siswa','SiswaController');
	Route::post('dosen/data-siswa-show','SiswaController@show')->name('data-siswa.show');
	Route::resource('dosen/data-visitasi','VisitasiController');

	 //Auth Dosen
	//Route::get('/signinvisitor', 'Auth\LoginController@showLoginForm')->name('signinvisitor');
	//Route::post('/signinvisitor', 'Auth\LoginController@login');
	//Route::post('logout','Auth\LoginController@logout')->name('logout');
});
//Pengelola atau Admin Route
Route::group(['namespace'=>'Pengelola'],function(){
	Route::get('pengelola/home','HomeController@index')->name('pengelola.home');
	Route::get('pengelola/ieds','IedsController@index')->name('pengelola.ieds');
	Route::get('pengelola/skorfuzzy','SkorfuzzyController@index')->name('pengelola.skorfuzzy');
	Route::get('pengelola/importfuzzy','SkorfuzzyController@indexImport')->name('pengelola.importfuzzy');
	Route::post('pengelola/kuotafuzzy','SkorfuzzyController@kuota')->name('pengelola.kuotafuzzy');
	Route::resource('pengelola/dosen','DosenController');
	Route::resource('pengelola/user','UserController');
	Route::resource('pengelola/datasau','SaudaraController');
	Route::resource('pengelola/dataketsau','KetsaudaraController');
	Route::resource('pengelola/datafoto','DatafotoController');
	Route::resource('pengelola/organisasi','OrganisasiController');
	Route::resource('pengelola/catatan','CatatanController');
	Route::resource('pengelola/berita','BeritaController');
	Route::resource('pengelola/dosen','DosenController');
	Route::resource('pengelola/nilai','NilaiController');
	Route::post('pengelola/nilaipertahun','NilaiController@show')->name('nilai.pertahun');
	Route::resource('pengelola/pendaftaran','PendaftaranController');
	Route::post('pengelola/pendaftaranpertahun','PendaftaranController@show')->name('pendaftaran.pertahun');
	Route::resource('pengelola/pengelola','PengelolaController');
	Route::resource('pengelola/penghasilan_ortu','Penghasilan_OrtuController');
	Route::post('pengelola/penghasilan_ortupertahun','Penghasilan_OrtuController@show')->name('penghasilan_ortu.pertahun');
	Route::resource('pengelola/rumah','RumahController');
	Route::post('pengelola/rumahpertahun','RumahController@show')->name('rumah.pertahun');
	Route::resource('pengelola/sekolah','SekolahController');
	Route::post('pengelola/sekolahpertahun','SekolahController@show')->name('sekolah.pertahun');
	Route::resource('pengelola/siswa','SiswaController');
	Route::post('pengelola/siswapertahun','SiswaController@show')->name('siswa.pertahun');
	Route::resource('pengelola/visitasi','VisitasiController');
	Route::resource('pengelola/prestasiekskul','PrestasiEkskulController');
	Route::post('pengelola/prestasiekskulshow','PrestasiEkskulController@show')->name('prestasiekskul.show');
	Route::resource('pengelola/banyaksiswapersekolah','BanyakSiswaPerSekolahController');
	Route::post('pengelola/banyaksiswapersekolahshow','BanyakSiswaPerSekolahController@show')->name('banyaksiswapersekolah.show');
	Route::resource('pengelola/banyaksiswaperprovinsi','BanyakSiswaPerProvinsiController');
	Route::post('pengelola/banyaksiswaperprovinsishow','BanyakSiswaPerProvinsiController@show')->name('banyaksiswaperprovinsi.show');
	Route::resource('pengelola/siswaperprodi','SiswaPerProdiController');
	Route::post('pengelola/siswaperprodishow','SiswaPerProdiController@show')->name('siswaperprodi.show');
	Route::resource('pengelola/banyaksiswaperkota','BanyakSiswaPerKotaController');
	Route::post('pengelola/banyaksiswaperkotashow','BanyakSiswaPerKotaController@show')->name('banyaksiswaperkota.show');
	Route::resource('pengelola/validasinilai','DataNilaiValidController');
	Route::post('pengelola/validasinilaishow','DataNilaiValidController@show')->name('validasinilai.show');
	Route::resource('pengelola/datanilaitidakvalid','DataNilaiTidakValidController');
	Route::resource('pengelola/laravel_google_chart', 'LaravelGoogleGraphController');
	Route::post('pengelola/laravel_google_chartshow','LaravelGoogleGraphController@show')->name('laravel_google_chart.show');
	Route::resource('pengelola/laravel_google_chart2', 'LaravelGoogleGraph2Controller');
	Route::post('pengelola/laravel_google_chart2show','LaravelGoogleGraph2Controller@show')->name('laravel_google_chart2.show');
	Route::resource('pengelola/validasijurusan','ValidasiJurusanController');
	Route::post('pengelola/validasijurusanshow','ValidasiJurusanController@show')->name('validasijurusan.show');

	Route::resource('pengelola/validasipenghasilan','ValidasiPenghasilanController');

	Route::get('pengelola/validatejurusan/validasi','ValidasiJurusanController@vld');
	Route::post('pengelola/validpenghasilan', 'ValidasiPenghasilanController@vld');
	Route::get('pengelola/validatenilai/validasi','DataNilaiValidController@vld');
	Route::resource('pengelola/jurusan', 'UpdateJurusanController');
	
	//Import Export Data Routes
	Route::get('pengelola/iofile','ImportExportController@index')->name('pengelola.importexport');
	Route::post('importsiswa', 'SiswaController@siswaImport')->name('siswa.import');
	Route::get('exportsiswa', 'SiswaController@siswaExport')->name('siswa.export');
	Route::post('importdosen', 'DosenController@Import')->name('dosen.import');
	Route::get('exportdosen', 'DosenController@Export')->name('dosen.export');
	Route::post('importvisitasi', 'VisitasiController@Import')->name('visitasi.import');
	Route::get('exportvisitasi', 'VisitasiController@Export')->name('visitasi.export');
	Route::post('importfuzzy','SkorfuzzyController@Import')->name('fuzzy.import');

	//Auth Pengelola
	Route::get('/signin', 'Auth\LoginController@showLoginForm')->name('signin');
	Route::post('/signin', 'Auth\LoginController@login');
	Route::post('logout','Auth\LoginController@logout')->name('logout');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

bidikmisi/app/Http/Controllers/Pengelola/BanyakSiswaPerKotaController.php
<?php

namespace App\Http\Controllers\Pengelola;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\pengelola\sekolah;
use Illuminate\Support\Facades\DB;
use PDF;

class BanyakSiswaPerKotaController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
        $showprov = DB::table('sekolahs')
        ->select('prov_sklh')
        ->groupBy('prov_sklh')
        ->get();
    	$sekolahs = DB::table('sekolahs')
        ->select('kota_sklh', DB::raw('count(*) as total'))
        ->groupBy('kota_sklh')
        ->get();
        return view('pengelola.banyaksiswaperkota',compact('sekolahs','showprov'));
    }

    public function show(Request $request){
        $prov_sklh = $request->prov_sklh;
        $tahun = $request->tahun;
        $sekolahs = DB::table('sekolahs')
        ->select('kota_sklh', DB::raw('count(*) as total'))
        ->where('prov_sklh', '=', $request->prov_sklh)
        ->whereYear('tgl_daftar', '=', $request->tahun)
        ->groupBy('kota_sklh')
        ->get();
        $pdf = PDF::loadView('pengelola.banyaksiswaperkotashow', compact('sekolahs','tahun','prov_sklh'));
        return $pdf->stream('banyaksiswaperkota.pdf');
    }


}

bidikmisi/app/Http/Controllers/Pengelola/BanyakSiswaPerProvinsiController.php
<?php

namespace App\Http\Controllers\Pengelola;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\pengelola\sekolah;
use Illuminate\Support\Facades\DB;
use PDF;

class BanyakSiswaPerProvinsiController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
    	$sekolahs = DB::table('sekolahs')
        ->select('prov_sklh', DB::raw('count(*) as total'))
        ->groupBy('prov_sklh')
        ->get();
        return view('pengelola.banyaksiswaperprovinsi',compact('sekolahs'));
    }
    public function show(Request $request)
    {
        $tahun = $request->tahun;
        $sekolahs = DB::table('sekolahs')
        ->select('prov_sklh', DB::raw('count(*) as total'))
        ->whereYear('tgl_daftar', '=', $request->tahun)
        ->groupBy('prov_sklh')
        ->get();
        $pdf = PDF::loadView('pengelola.banyaksiswaperprovinsishow', compact('sekolahs','tahun'));
        return $pdf->stream('banyaksiswaperprovinsi.pdf');
    }
}

bidikmisi/app/Http/Controllers/Pengelola/BanyakSiswaPerSekolahController.php
<?php

namespace App\Http\Controllers\Pengelola;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\pengelola\sekolah;
use Illuminate\Support\Facades\DB;
use PDF;

class BanyakSiswaPerSekolahController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
    	$sekolahs = DB::table('sekolahs')
        ->select('nama_sklh', DB::raw('count(*) as total'))
        ->groupBy('nama_sklh')
        ->get();
        return view('pengelola.banyaksiswapersekolah',compact('sekolahs'));
    }
    public function show(Request $request)
    {
        $tahun = $request->tahun;
        $sekolahs = DB::table('sekolahs')
        ->select('nama_sklh', DB::raw('count(*) as total'))
        ->whereYear('tgl_daftar', '=', $request->tahun)
        ->groupBy('nama_sklh')
        ->get();
        $pdf = PDF::loadView('pengelola.banyaksiswapersekolahshow', compact('sekolahs','tahun'));
        return $pdf->stream('banyaksiswapersekolah.pdf');
    }
    	
}

bidikmisi/app/Http/Controllers/Pengelola/BeritaController.php
<?php

namespace App\Http\Controllers\Pengelola;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\pengelola\berita;

class BeritaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
        $beritas = berita::all();
        return view('pengelola.berita.show',compact('beritas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('pengelola.berita.berita');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'judul'=>'required',
            'isi'=>'required',
            ]);
        $berita = new berita;
        $berita->judul=$request->judul;
        $berita->isi=$request->isi;
        $berita->slug=str_slug($request->judul);
        $berita->save();

        return redirect(route('berita.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $berita=berita::where('id',$id)->first();

        return view('pengelola.berita.edit',compact('berita'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'judul'=>'required',
            'isi'=>'required',
            ]);

         $berita = berita::find($id);
        $berita->judul=$request->judul;
        $berita->isi=$request->isi;
        $berita->slug=str_slug($request->judul);
        $berita->save();

        return redirect(route('berita.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        berita::where('id',$id)->delete();
        return redirect()->back();
    }
}

bidikmisi/app/Http/Controllers/Pengelola/CatatanController.php
<?php

namespace App\Http\Controllers\Pengelola;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\pengelola\data_catatan;
use App\Model\pengelola\siswa;

class CatatanController extends Controller
{
    public function __construct()
    {
    	$this->middleware('auth:pengelola');
    }

    public function index()
    {
    	$data = data_catatan::all();
    	return view('pengelola.catatan.show', compact('data'));
    }
    public function create()
    {
    	$siswa = siswa::all();
        $data = data_catatan::all();
    	return view('pengelola.catatan.catatan', compact('data','siswa'));
    }
    public function store(Request $request)
    {
        $data = new data_catatan;
        $data->nisn=$request->nisn;
        $data->pemahaman1=$request->pemahaman1;
        $data->pemahaman2=$request->pemahaman2;
        $data->harapan1=$request->harapan1;
        $data->harapan2=$request->harapan2;
        $data->catatan=$request->catatan;
        $data->ijazah=$request->ijazah;
        $data->rapor=$request->rapor;
        $data->sertifikat=$request->sertifikat;
        $data->kk=$request->kk;
        $data->surat_peng=$request->surat_peng;
        $data->bpjs=$request->bpjs;
        $data->kis=$request->kis;
        $data->kip=$request->kip;
        $data->ksks=$request->ksks;
        $data->raskin=$request->raskin;
        $data->pbb=$request->pbb;
        $data->bukti_listrik=$request->bukti_listrik;
        $data->surat_data=$request->surat_data;
        $data->penilaian=$request->penilaian;
        $data->save();

        return redirect(route('catatan.index'));
    }
    public function edit($id)
    {
        $data=data_catatan::where('nisn',$id)->first();
        $siswa=siswa::all();
        return view('pengelola.catatan.edit',compact('data','siswa'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = data_catatan::find($id);
        //$pengelolas->nidn=$request->nidn;
        //$pengelolas->username=$request->username;
        //$pengelolas->password=bcrypt($request->password);
        //$pengelolas->level=$request->level;
        $data->update($request->all());

        return redirect(route('catatan.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        data_catatan::where('nisn',$id)->delete();
        return redirect()->back();
    }
}

bidikmisi/resources/views/pengelola/pengelola/edit.blade.php
@extends('pengelola.layouts.app')

@section('main-content')
<div class="content-wrapper">
  <section class="content">
    <div class="row">
      <div class="col-md-12">
        <div class="box box-primary">
          <div class="box-header with-border">
              <h3 class="box-title">Form pengelola</h3>
          </div>

            @include('includes.messages')

          <form role="form" action="{{ route('pengelola.update',$pengelola->id)}}" method="post">
          {{ csrf_field()}}
          {{ method_field('PATCH')}}
           <div class="box-body">
            <div class="form-group">
              <label for="email">E-mail</label>
              <input type="email" class="form-control" id="email" name="email" placeholder="email" value="{{ $pengelola->email}}">
            </div>
          </div>
          <div class="box-body">
            <div class="form-group">
              <label for="text">Password</label>
              <input type="password" class="form-control" id="password" name="password" placeholder="password" value="{{ $pengelola->password}}">
            </div>
          </div>
          <div class="box-body">
            <div class="form-group">
              <label for="nama">Nama</label>
              <input type="text" class="form-control" id="nama" name="nama" placeholder="nama" value="{{ $pengelola->nama}}">
            </div>
          </div>
          <div class="box-body">
            <div class="form-group">
              <label for="tempat_lahir">Tempat Lahir</label>
              <input type="text" class="form-control" id="tempat_lahir" name="tempat_lahir" placeholder="tempat_lahir" value="{{ $pengelola->tempat_lahir}}">
            </div>
          </div>
          <div class="box-body">
            <div class="form-group">
              <label for="tgl_lahir">Tanggal Lahir</label>
              <input type="date" class="form-control" id="tgl_lahir" name="tgl_lahir" placeholder="tgl_lahir" value="{{ $pengelola->tgl_lahir}}">
            </div>
          </div>
          <div class="box-body">
           <div class="form-group">
              <label for="jekel">Jenis Kelamin</label>
               <br>
              <input type="radio" name="jekel" value="P" {{$pengelola->jekel == 'P' ? 'checked' :''}}> Perempuan
              <br>
              <input type="radio" name="jekel" value="L" {{$pengelola->jekel == 'L' ? 'checked' :''}}> Laki-Laki
            </div>
          </div>
          <div class="box-body">
            <div class="form-group">
              <label for="no_hp">No. HP</label>
              <input type="text" class="form-control" id="no_hp" name="no_hp" placeholder="no_hp" value="{{ $pengelola->no_hp}}">
            </div>
          </div>
          <div class="box-body">
            <div class="form-group">
              <label for="alamat">Alamat</label>
              <input type="text" class="form-control" id="alamat" name="alamat" placeholder="alamat" value="{{ $pengelola->alamat}}">
            </div>
          </div>
          <div class="box-footer">
              <button type="submit" class="btn btn-primary">Simpan</button>
              <a href='{{route("pengelola.index")}}' class="btn btn-warning">Kembali</a>
          </div>
          </form>
        </div>
      </div>
      </div>
  </section>
</div>
  @endsection

bidikmisi/resources/views/pengelola/pengelola/pengelola.blade.php
@extends('pengelola.layouts.app')

@section('main-content')
<div class="content-wrapper">
  <section class="content">
    <div class="row">
      <div class="col-md-12">
        <div class="box box-primary">
          <div class="box-header with-border">
              <h3 class="box-title">Form Pengelola</h3>
          </div>

            @include('includes.messages')

          <form role="form" action="{{ route('pengelola.store')}}" method="post">
          {{ csrf_field()}}
          <div class="box-body">
            <div class="form-group">
              <label for="email">E-mail</label>
              <input type="email" class="form-control" id="email" name="email" placeholder="email">
            </div>
          </div>
          <div class="box-body">
            <div class="form-group">
              <label for="password">Password</label>
              <input type="text" class="form-control" id="password" name="password" placeholder="password">
            </div>
          </div>
          <div class="box-body">
            <div class="form-group">
              <label for="nama">Nama</label>
              <input type="text" class="form-control" id="nama" name="nama" placeholder="nama">
            </div>
          </div>
          <div class="box-body">
            <div class="form-group">
              <label for="tempat_lahir">Tempat Lahir</label>
              <input type="text" class="form-control" id="tempat_lahir" name="tempat_lahir" placeholder="tempat_lahir">
            </div>
          </div>
          <div class="box-body">
            <div class="form-group">
              <label for="tgl_lahir">Tanggal Lahir</label>
              <input type="date" class="form-control" id="tgl_lahir" name="tgl_lahir" placeholder="tgl_lahir">
            </div>
          </div>
          <div class="box-body">
            <div class="form-group">
              <label for="jekel">Jenis Kelamin</label>
              <br>
              <input type="radio" name="jekel" value="P" checked="true">Perempuan
              <br>
              <input type="radio" name="jekel" value="L">Laki-Laki
            </div>
          </div>
          <div class="box-body">
            <div class="form-group">
              <label for="no_hp">No. HP</label>
              <input type="text" class="form-control" id="no_hp" name="no_hp" placeholder="no_hp">
            </div>
          </div>
          <div class="box-body">
            <div class="form-group">
              <label for="alamat">Alamat</label>
              <input type="text" class="form-control" id="alamat" name="alamat" placeholder="alamat">
            </div>
          </div>
         
          
          <div class="box-footer">
              <button type="submit" class="btn btn-primary">Simpan</button>
              <a href='{{route("pengelola.index")}}' class="btn btn-warning">Kembali</a>
          </div>
          </form>
        </div>
      </div>
      </div>
  </section>
</div>
  @endsection

bidikmisi/resources/views/pengelola/pengelola/show.blade.php
@extends('pengelola.layouts.app')

@section('head')
<!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('pengelola/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }} ">
@endsection

@section('main-content')
<div class="content-wrapper">

    <!-- Main content -->
    <section class="content container-fluid">

      <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Data pengelola</h3>
              <a class='col-lg-offset-10 btn btn-success' href="{{ route('pengelola.create')}}">Tambah Pengelola</a>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive">
              <table id="myTable" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>No.</th>
                  <th>Email</th>
                  <th>Password</th>
                  <th>Nama</th>
                  <th>Tempat Lahir</th>
                  <th>Tanggal Lahir</th>
                  <th>JK</th>
                  <th>No. HP</th>
                  <th>Alamat</th>
                  <th width="5%">Aksi</th>
                </tr>
                </thead>
                <tbody>
                  @foreach ($pengelolas as $pengelola)
                  <tr>
                    <td>{{ $loop->index + 1 }}</td>
                    <td>{{ $pengelola->email}}</td>
                    <td>{{ $pengelola->password}}</td>
                    <td>{{ $pengelola->nama}}</td>
                    <td>{{ $pengelola->tempat_lahir}}</td>
                    <td>{{ $pengelola->tgl_lahir}}</td>
                    <td>{{ $pengelola->jekel}}</td>
                    <td>{{ $pengelola->no_hp}}</td>
                    <td>{{ $pengelola->alamat}}</td>
                
                    <td><a href="{{route('pengelola.edit',$pengelola->id)}}"><span class="glyphicon glyphicon-edit"></span></a>
                      <form id="delete-form-{{ $pengelola->id }}" method="post" action="{{route('pengelola.destroy',$pengelola->id)}}" style="display: none">
                        {{csrf_field()}}
                        {{method_field('DELETE')}}
                      </form>
                      <a href="" onclick="
                      if(confirm('Yakin Ingin Menghapus Data pengelola?'))
                        {
                          event.preventDefault();
                          document.getElementById('delete-form-{{ $pengelola->id }}').submit();
                        } else {
                          event.preventDefault();
                        }"><span class="glyphicon glyphicon-trash"></span></a>
                        
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table> 
            </div>
          </div>

        </div>
      </div>
    </section>

    </section>
    <!-- /.content -->
  </div>

@endsection

@section('script')
<!-- DataTables -->
<script src="{{ asset('pengelola/bower_components/datatables.net/js/jquery.dataTables.min.js') }} "></script>
<script src="{{ asset('pengelola/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }} "></script>
<script>
  $(function () {
    $('#myTable').DataTable()
  })
</script>
@endsection