bidikmisi/routes/web.php
<?php
//User Routes
Route::group(['namespace'=>'User'],function(){
	Route::get('/','HomeController@index')->name('user.home');
	Route::get('berita/{slug}','HomeController@show')->name('berita');
	Route::resource('user/jadwal_visitasi','VisitasiController');
	Route::resource('user/banyaksiswa_persekolah','BanyakSiswaPerSekolahController');
	Route::post('user/banyaksiswa_persekolahshow','BanyakSiswaPerSekolahController@show')->name('banyaksiswa_persekolah.show');
	Route::resource('user/banyaksiswa_perkota','BanyakSiswaPerKotaController');
	Route::post('user/banyaksiswa_perkotashow','BanyakSiswaPerKotaController@show')->name('banyaksiswa_perkota.show');
	Route::resource('user/banyaksiswa_perprovinsi','BanyakSiswaPerProvinsiController');
	Route::post('user/banyaksiswa_perprovinsishow','BanyakSiswaPerProvinsiController@show')->name('banyaksiswa_perprovinsi.show');
	Route::resource('user/laravelgooglechart','LaravelGoogleGraphController');
	Route::post('user/laravelgooglechartshow','LaravelGoogleGraphController@show')->name('laravelgooglechart.show');
	Route::resource('user/laravelgooglechart2','LaravelGoogleGraph2Controller');
	Route::post('user/laravelgooglechart2show','LaravelGoogleGraph2Controller@show')->name('laravelgooglechart2.show');
	Route::resource('user/prestasi_ekskul','PrestasiEkskulController');
	Route::post('user/prestasi_ekskulshow','PrestasiEkskulController@show')->name('prestasi_ekskul.show');
	Route::resource('user/validasi_nilai','ValidasiNilaiController');
	Route::post('user/validasi_nilaishow','ValidasiNilaiController@show')->name('validasi_nilai.show');
	Route::resource('user/validasi_jurusan','ValidasiJurusanController');
	Route::post('user/validasi_jurusanshow','ValidasiJurusanController@show')->name('validasi_jurusan.show');
});
//Dosen Route
Route::group(['namespace'=>'Dosen'],function(){
	Route::get('dosen/home','HomeController@index')->name('dosen.home');
	Route::resource('dosen/data-dosen','DosenController');
	Route::resource('dosen/data-nilai','NilaiController');
	Route::post('dosen/data-nilai-show','NilaiController@show')->name('data-nilai.show');
	Route::resource('dosen/data-pendaftaran','PendaftaranController');
	Route::post('dosen/data-pendaftaran-show','PendaftaranController@show')->name('data-pendaftaran.show');
	Route::resource('dosen/data-penghasilan_ortu','Penghasilan_OrtuController');
	Route::post('dosen/data-penghasilan_ortu-show','Penghasilan_OrtuController@show')->name('data-penghasilan_ortu.show');
	Route::resource('dosen/data-rumah','RumahController');
	Route::post('dosen/data-rumah-show','RumahController@show')->name('data-rumah.show');
	Route::resource('dosen/data-sekolah','SekolahController');
	Route::post('dosen/data-sekolah-show','SekolahController@show')->name('data-sekolah.show');
	Route::resource('dosen/data-siswa','SiswaController');
	Route::post('dosen/data-siswa-show','SiswaController@show')->name('data-siswa.show');
	Route::resource('dosen/data-visitasi','VisitasiController');

	 //Auth Dosen
	//Route::get('/signinvisitor', 'Auth\LoginController@showLoginForm')->name('signinvisitor');
	//Route::post('/signinvisitor', 'Auth\LoginController@login');
	//Route::post('logout','Auth\LoginController@logout')->name('logout');
});
//Pengelola atau Admin Route
Route::group(['namespace'=>'Pengelola'],function(){
	Route::get('pengelola/home','HomeController@index')->name('pengelola.home');
	Route::get('pengelola/ieds','IedsController@index')->name('pengelola.ieds');
	Route::get('pengelola/skorfuzzy','SkorfuzzyController@index')->name('pengelola.skorfuzzy');
	Route::get('pengelola/importfuzzy','SkorfuzzyController@indexImport')->name('pengelola.importfuzzy');
	Route::post('pengelola/kuotafuzzy','SkorfuzzyController@kuota')->name('pengelola.kuotafuzzy');
	Route::resource('pengelola/dosen','DosenController');
	Route::resource('pengelola/user','UserController');
	Route::resource('pengelola/datasau','SaudaraController');
	Route::resource('pengelola/dataketsau','KetsaudaraController');
	Route::resource('pengelola/datafoto','DatafotoController');
	Route::resource('pengelola/organisasi','OrganisasiController');
	Route::resource('pengelola/catatan','CatatanController');
	Route::resource('pengelola/berita','BeritaController');
	Route::resource('pengelola/dosen','DosenController');
	Route::resource('pengelola/nilai','NilaiController');
	Route::post('pengelola/nilaipertahun','NilaiController@show')->name('nilai.pertahun');
	Route::resource('pengelola/pendaftaran','PendaftaranController');
	Route::post('pengelola/pendaftaranpertahun','PendaftaranController@show')->name('pendaftaran.pertahun');
	Route::resource('pengelola/pengelola','PengelolaController');
	Route::resource('pengelola/penghasilan_ortu','Penghasilan_OrtuController');
	Route::post('pengelola/penghasilan_ortupertahun','Penghasilan_OrtuController@show')->name('penghasilan_ortu.pertahun');
	Route::resource('pengelola/rumah','RumahController');
	Route::post('pengelola/rumahpertahun','RumahController@show')->name('rumah.pertahun');
	Route::resource('pengelola/sekolah','SekolahController');
	Route::post('pengelola/sekolahpertahun','SekolahController@show')->name('sekolah.pertahun');
	Route::resource('pengelola/siswa','SiswaController');
	Route::post('pengelola/siswapertahun','SiswaController@show')->name('siswa.pertahun');
	Route::resource('pengelola/visitasi','VisitasiController');
	Route::resource('pengelola/prestasiekskul','PrestasiEkskulController');
	Route::post('pengelola/prestasiekskulshow','PrestasiEkskulController@show')->name('prestasiekskul.show');
	Route::resource('pengelola/banyaksiswapersekolah','BanyakSiswaPerSekolahController');
	Route::post('pengelola/banyaksiswapersekolahshow','BanyakSiswaPerSekolahController@show')->name('banyaksiswapersekolah.show');
	Route::resource('pengelola/banyaksiswaperprovinsi','BanyakSiswaPerProvinsiController');
	Route::post('pengelola/banyaksiswaperprovinsishow','BanyakSiswaPerProvinsiController@show')->name('banyaksiswaperprovinsi.show');
	Route::resource('pengelola/siswaperprodi','SiswaPerProdiController');
	Route::post('pengelola/siswaperprodishow','SiswaPerProdiController@show')->name('siswaperprodi.show');
	Route::resource('pengelola/banyaksiswaperkota','BanyakSiswaPerKotaController');
	Route::post('pengelola/banyaksiswaperkotashow','BanyakSiswaPerKotaController@show')->name('banyaksiswaperkota.show');
	Route::resource('pengelola/validasinilai','DataNilaiValidController');
	Route::post('pengelola/validasinilaishow','DataNilaiValidController@show')->name('validasinilai.show');
	Route::resource('pengelola/datanilaitidakvalid','DataNilaiTidakValidController');
	Route::resource('pengelola/laravel_google_chart', 'LaravelGoogleGraphController');
	Route::post('pengelola/laravel_google_chartshow','LaravelGoogleGraphController@show')->name('laravel_google_chart.show');
	Route::resource('pengelola/laravel_google_chart2', 'LaravelGoogleGraph2Controller');
	Route::post('pengelola/laravel_google_chart2show','LaravelGoogleGraph2Controller@show')->name('laravel_google_chart2.show');
	Route::resource('pengelola/validasijurusan','ValidasiJurusanController');
	Route::post('pengelola/validasijurusanshow','ValidasiJurusanController@show')->name('validasijurusan.show');

	Route::resource('pengelola/validasipenghasilan','ValidasiPenghasilanController');

	Route::get('pengelola/validatejurusan/validasi','ValidasiJurusanController@vld');
	Route::post('pengelola/validpenghasilan', 'ValidasiPenghasilanController@vld');
	Route::get('pengelola/validatenilai/validasi','DataNilaiValidController@vld');
	Route::resource('pengelola/jurusan', 'UpdateJurusanController');
	
	//Import Export Data Routes
	Route::get('pengelola/iofile','ImportExportController@index')->name('pengelola.importexport');
	Route::post('importsiswa', 'SiswaController@siswaImport')->name('siswa.import');
	Route::get('exportsiswa', 'SiswaController@siswaExport')->name('siswa.export');
	Route::post('importdosen', 'DosenController@Import')->name('dosen.import');
	Route::get('exportdosen', 'DosenController@Export')->name('dosen.export');
	Route::post('importvisitasi', 'VisitasiController@Import')->name('visitasi.import');
	Route::get('exportvisitasi', 'VisitasiController@Export')->name('visitasi.export');
	Route::post('importfuzzy','SkorfuzzyController@Import')->name('fuzzy.import');

	//Auth Pengelola
	Route::get('/signin', 'Auth\LoginController@showLoginForm')->name('signin');
	Route::post('/signin', 'Auth\LoginController@login');
	Route::post('logout','Auth\LoginController@logout')->name('logout');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

bidikmisi/app/Http/Controllers/Dosen/DosenController.php
<?php

namespace App\Http\Controllers\Dosen;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\pengelola\dosen;

class DosenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
        $dosens = dosen::all();
        return view('dosen.data-dosen',compact('dosens'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       
    }

    
}

bidikmisi/app/Http/Controllers/Dosen/HomeController.php
<?php

namespace App\Http\Controllers\Dosen;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
    	return view('dosen/home');
    }
}

bidikmisi/app/Http/Controllers/Dosen/NilaiController.php
<?php

namespace App\Http\Controllers\Dosen;

use App\Http\Controllers\Controller;
use App\Model\pengelola\nilai;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Auth;

class NilaiController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
        $user = Auth::user()->nidn;
        $nilais = DB::select( DB::raw("SELECT * FROM nilais WHERE nisn IN(SELECT nisn FROM siswas WHERE id_visitor1=$user OR id_visitor2=$user )"));
        //$nilais = nilai::all();
        return view('dosen.data-nilai',compact('nilais'));
    }
    public function show(Request $request)
    {
        $nilais = DB::table('nilais')
        ->whereYear('tgl_daftar', '=', $request->tahun)
        ->get();
        return view('dosen.data-nilai-show',compact('nilais'));
    }
   
}

bidikmisi/app/Http/Controllers/Dosen/PendaftaranController.php
<?php

namespace App\Http\Controllers\Dosen;

use App\Http\Controllers\Controller;
use App\Model\pengelola\pendaftaran;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Auth;

class PendaftaranController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
        $user = Auth::user()->nidn;
        $pendaftarans = DB::select( DB::raw("SELECT * FROM pendaftarans WHERE nisn IN(SELECT nisn FROM siswas WHERE id_visitor1=$user OR id_visitor2=$user )"));
        //$pendaftarans = pendaftaran::all();
        return view('dosen.data-pendaftaran',compact('pendaftarans'));
    }
    public function show(Request $request)
    {
        $pendaftarans = DB::table('pendaftarans')
        ->whereYear('tgl_daftar', '=', $request->tahun)
        ->get();
        return view('dosen.data-pendaftaran-show',compact('pendaftarans'));
    }
}

bidikmisi/app/Http/Controllers/Dosen/Penghasilan_OrtuController.php
<?php

namespace App\Http\Controllers\Dosen;

use App\Http\Controllers\Controller;
use App\Model\pengelola\penghasilan_ortu;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Auth;

class Penghasilan_OrtuController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
        $user = Auth::user()->nidn;
        $penghasilan_ortus = DB::select( DB::raw("SELECT * FROM penghasilan_ortus WHERE nisn IN(SELECT nisn FROM siswas WHERE id_visitor1=$user OR id_visitor2=$user )"));
        //$penghasilan_ortus = penghasilan_ortu::all();
        return view('dosen.data-penghasilan_ortu',compact('penghasilan_ortus'));
    }
    public function show(Request $request)
    {
        $penghasilan_ortus = DB::table('penghasilan_ortus')
        ->whereYear('tgl_daftar', '=', $request->tahun)
        ->get();
        return view('dosen.data-penghasilan_ortu-show',compact('penghasilan_ortus'));
    }
}

bidikmisi/app/Http/Controllers/Dosen/RumahController.php
<?php

namespace App\Http\Controllers\Dosen;

use App\Http\Controllers\Controller;
use App\Model\pengelola\rumah;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Auth;

class RumahController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
        $user = Auth::user()->nidn;
        $rumahs = DB::select( DB::raw("SELECT * FROM rumahs WHERE nisn IN(SELECT nisn FROM siswas WHERE id_visitor1=$user OR id_visitor2=$user )"));
        //$rumahs = rumah::all();
        return view('dosen.data-rumah',compact('rumahs'));
    }
    public function show(Request $request)
    {
        $rumahs = DB::table('rumahs')
        ->whereYear('tgl_daftar', '=', $request->tahun)
        ->get();
        return view('dosen.data-rumah-show',compact('rumahs'));
    }
}

bidikmisi/app/Http/Controllers/Dosen/SekolahController.php
<?php

namespace App\Http\Controllers\Dosen;

use App\Http\Controllers\Controller;
use App\Model\pengelola\sekolah;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Auth;

class SekolahController extends Controller
{
   public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
        $user = Auth::user()->nidn;
        $sekolahs = DB::select( DB::raw("SELECT * FROM sekolahs WHERE nisn IN(SELECT nisn FROM siswas WHERE id_visitor1=$user OR id_visitor2=$user )"));
        //$sekolahs = sekolah::all();
        return view('dosen.data-sekolah',compact('sekolahs'));
    }
   public function show(Request $request)
    {
        $sekolahs = DB::table('sekolahs')
        ->whereYear('tgl_daftar', '=', $request->tahun)
        ->get();
        return view('dosen.data-sekolah-show',compact('sekolahs'));
    }
}

bidikmisi/app/Http/Controllers/Dosen/SiswaController.php
<?php

namespace App\Http\Controllers\Dosen;

use App\Http\Controllers\Controller;
use App\Model\pengelola\siswa;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Auth;

class SiswaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:pengelola');
    }

    public function index()
    {
        $user = Auth::user()->nidn;
        $siswas = siswa::where('id_visitor1',$user)->orWhere('id_visitor2',$user)->get();
        return view('dosen.data-siswa',compact('siswas'));
    }

    public function show(Request $request)
    {
        $siswas = DB::table('siswas')
        ->whereYear('tgl_daftar', '=', $request->tahun)
        ->get();
        return view('dosen.data-siswa-show',compact('siswas'));
    }
}

bidikmisi/app/Http/Controllers/Dosen/VisitasiController.php
<?php

namespace App\Http\Controllers\Dosen;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\Model\pengelola\visitasi;
use Auth;

class VisitasiController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
        $user = Auth::user()->nidn;
        $visitasis = DB::table('visitasis as a')
        ->leftjoin('dosens as b','b.nidn', '=', 'a.nidn')
        ->leftjoin('siswas as c','c.nisn', '=', 'a.nisn')
        ->leftjoin('dosens as d', 'd.nidn', '=', 'a.nidn2')
        ->select('a.*', 'b.nama_dosen as nama_dosen1','d.nama_dosen as nama_dosen2','c.nama_siswa','c.alamat')
        ->where('c.id_visitor1',$user)
        ->orWhere('c.id_visitor2', $user)
        ->get();
        return view('dosen.data-visitasi',compact('visitasis'));
    }
    public function show($id)
    {
       
    }
}

bidikmisi/app/Http/Controllers/Pengelola/BanyakSiswaPerKotaController.php
<?php

namespace App\Http\Controllers\Pengelola;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\pengelola\sekolah;
use Illuminate\Support\Facades\DB;
use PDF;

class BanyakSiswaPerKotaController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth:pengelola');
    }
    public function index()
    {
        $showprov = DB::table('sekolahs')
        ->select('prov_sklh')
        ->groupBy('prov_sklh')
        ->get();
    	$sekolahs = DB::table('sekolahs')
        ->select('kota_sklh', DB::raw('count(*) as total'))
        ->groupBy('kota_sklh')
        ->get();
        return view('pengelola.banyaksiswaperkota',compact('sekolahs','showprov'));
    }

    public function show(Request $request){
        $prov_sklh = $request->prov_sklh;
        $tahun = $request->tahun;
        $sekolahs = DB::table('sekolahs')
        ->select('kota_sklh', DB::raw('count(*) as total'))
        ->where('prov_sklh', '=', $request->prov_sklh)
        ->whereYear('tgl_daftar', '=', $request->tahun)
        ->groupBy('kota_sklh')
        ->get();
        $pdf = PDF::loadView('pengelola.banyaksiswaperkotashow', compact('sekolahs','tahun','prov_sklh'));
        return $pdf->stream('banyaksiswaperkota.pdf');
    }


}

bidikmisi/resources/views/pengelola/dosen/dosen.blade.php
@extends('pengelola.layouts.app')

@section('main-content')
<div class="page-content-wrap">
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-colorful">
          <div class="panel-heading">
              <h3 class="panel-title">Form Dosen</h3>
          </div>

            @include('includes.messages')

          <form role="form" action="{{ route('dosen.store')}}" method="post">
          {{ csrf_field()}}
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="nidn">NIDN</label>
              <div class="col-md-9 col-xs-12">
                <input type="text" class="form-control" id="nidn" name="nidn" placeholder="NIDN">
              </div>
            </div>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="nama_dosen">Nama Dosen</label>
              <div class="col-md-9 col-xs-12">
                <input type="text" class="form-control" id="nama_dosen" name="nama_dosen" placeholder="Nama Dosen">
              </div>
            </div>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="tempat_lahir">Tempat Lahir</label>
              <div class="col-md-9 col-xs-12">
                <input type="text" class="form-control" id="tempat_lahir" name="tempat_lahir" placeholder="Tempat Lahir">
              </div>
            </div>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="tgl_lahir">Tanggal Lahir</label>
              <div class="col-md-9 col-xs-12">
                <input type="text" class="form-control" id="tgl_lahir" name="tgl_lahir" placeholder="Tanggal Lahir">
              </div>
            </div>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="jekel">Jenis Kelamin</label>
              <div class="col-md-9 col-xs-12">
                <label class="check"><input type="radio" class="iradio" name="jekel" value="L" checked="true">Laki-Laki</label>
                <br>
                <label class="check"><input type="radio" class="iradio" name="jekel" value="P">Perempuan</label>
              </div>
            </div>
          </div>
           {{-- <div class="box-body">
            <div class="form-group">
              <label for="no_hp">No. HP</label>
              <input type="text" class="form-control" id="no_hp" name="no_hp" placeholder="no_hp">
            </div>
          </div>
           <div class="box-body">
            <div class="form-group">
              <label for="alamat">Alamat</label>
              <input type="text" class="form-control" id="alamat" name="alamat" placeholder="alamat">
            </div>
          </div>
           --}}
          <div class="panel-footer">
              <button type="submit" class="btn btn-primary">Simpan</button>
              <a href='{{route("dosen.index")}}' class="btn btn-warning">Kembali</a>
          </div>
          </form>
        </div>
      </div>
      </div>
</div>
  @endsection

bidikmisi/resources/views/pengelola/dosen/edit.blade.php
@extends('pengelola.layouts.app')

@section('main-content')
<div class="page-content-wrap">
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-colorful">
          <div class="panel-heading">
              <h3 class="panel-title">Form dosen</h3>
          </div>

            @include('includes.messages')

          <form role="form" action="{{ route('dosen.update',$dosen->nidn)}}" method="post">
          {{ csrf_field()}}
          {{ method_field('PATCH')}}
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="nidn">NIDN</label>
              <div class="col-md-9 col-xs-12">
                <input type="text" class="form-control" id="nidn" name="nidn" placeholder="NIDN" value="{{$dosen->nidn}}">
              </div>
            </div>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="nama_dosen">Nama Dosen</label>
              <div class="col-md-9 col-xs-12">
                <input type="text" class="form-control" id="nama_dosen" name="nama_dosen" placeholder="Nama Dosen" value="{{$dosen->nama_dosen}}">
              </div>
            </div>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="tempat_lahir">Tempat Lahir</label>
              <div class="col-md-9 col-xs-12">
                <input type="text" class="form-control" id="tempat_lahir" name="tempat_lahir" placeholder="Tempat Lahir" value="{{$dosen->tempat_lahir}}">
              </div>
            </div>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="tgl_lahir">Tanggal Lahir</label>
              <div class="col-md-9 col-xs-12">
                <input type="text" class="form-control" id="tgl_lahir" name="tgl_lahir" placeholder="Tanggal Lahir" value="{{$dosen->tgl_lahir}}">
              </div>
            </div>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-md-2 col-xs-12 control-label" for="jekel">Jenis Kelamin</label>
              <div class="col-md-9 col-xs-12">
                <label class="check"><input type="radio" class="iradio" name="jekel" value="L" {{$dosen->jekel == 'L' ? 'checked' :''}}>Laki-Laki</label>
                <br>
                <label class="check"><input type="radio" class="iradio" name="jekel" value="P" {{$dosen->jekel == 'P' ? 'checked' :''}}>Perempuan</label>
              </div>
            </div>
          </div>
           {{-- <div class="box-body">
            <div class="form-group">
              <label for="no_hp">No. HP</label>
              <input type="text" class="form-control" id="no_hp" name="no_hp" placeholder="no_hp" value="{{ $dosen->no_hp}}">
            </div>
          </div>
           <div class="box-body">
            <div class="form-group">
              <label for="alamat">Alamat</label>
              <input type="text" class="form-control" id="alamat" name="alamat" placeholder="alamat" value="{{ $dosen->alamat}}">
            </div>
          </div> --}}

          <div class="panel-footer">
              <button type="submit" class="btn btn-primary">Simpan</button>
              <a href='{{route("dosen.index")}}' class="btn btn-warning">Kembali</a>
          </div>
          </form>
        </div>
      </div>
      </div>
  </section>
</div>
  @endsection

bidikmisi/resources/views/pengelola/dosen/show.blade.php
@extends('pengelola.layouts.app')

@section('main-content')
<div class="page-content-wrap">
      <div class="row">
        <div class="col-md-12">
          <div class="panel panel-colorful animated fadeIn">
            <div class="panel-heading">
              <h3 class="panel-title">Data Visitor</h3>
            </div>
            <!-- /.box-header -->
            <div class="panel-body table-responsive">
              <a class=' btn btn-success' href="{{ route('dosen.create')}}">Tambah Visitor</a>
              <button class="btn btn-success" data-toggle="modal" data-target="#modal_iedosen">Import Data</button>
              <a class='btn btn-success' href="{{ route('dosen.export')}}">Export Data</a>
            </div>
            <div class="panel-body table-responsive">
              <table class="table datatable table-hover">
                <thead>
                <tr>
                  <th>No.</th>
                  <th>NIDN</th>
                  <th>Nama Visitor</th>
                  <th>Tempat Lahir</th>
                  <th>Tanggal Lahir</th>
                  <th>JK</th>
                 {{--  <th>No. HP</th>
                  <th>Alamat</th> --}}
                  <th width="5%">Aksi</th>
                </tr>
                </thead>
                <tbody>
                  @foreach ($dosens as $dosen)
                  <tr>
                    <td>{{ $loop->index + 1 }}</td>
                    <td>{{ $dosen->nidn }}</td>
                    <td>{{ $dosen->nama_dosen }}</td>
                    <td>{{ $dosen->tempat_lahir }}</td>
                    <td>{{ $dosen->tgl_lahir }}</td>
                    <td>{{ $dosen->jekel }}</td>
                    {{-- <td>{{ $dosen->no_hp }}</td>
                    <td>{{ $dosen->alamat }}</td> --}}
                    <td><a href="{{route('dosen.edit',$dosen->nidn)}}"><span class="glyphicon glyphicon-edit"></span></a>
                      <form id="delete-form-{{ $dosen->nidn }}" method="post" action="{{route('dosen.destroy',$dosen->nidn)}}" style="display: none">
                        {{csrf_field()}}
                        {{method_field('DELETE')}}
                      </form>
                      <a href="" onclick="
                      if(confirm('Yakin Ingin Menghapus Data dosen?'))
                        {
                          event.preventDefault();
                          document.getElementById('delete-form-{{ $dosen->nidn }}').submit();
                        } else {
                          event.preventDefault();
                        }"><span class="glyphicon glyphicon-trash"></span></a>
                        
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table> 
            </div>
          </div>

        </div>
      </div>
    <!-- /.content -->
  </div>

@endsection

@section('script')
<!-- DataTables -->
<script type="text/javascript" src="{{asset('js/plugins/datatables/jquery.dataTables.min.js')}}"></script> 
@endsection